version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/streamlit-app
hooks:
  ApplicationStop:
    - location: stop_app.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start_app.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: validate_app.sh
      timeout: 60
      runas: root
